rvm:
  - 1.9.3
  - 2.0.0-p648
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-19mode
env:
  - TEST="test/test_*"
  - TEST="test/test_standard.rb"
  - DISABLE_REFINEMENTS=1 TEST="test/test_*"
  - DISABLE_REFINEMENTS=1 TEST="test/test_standard.rb"
matrix:
  exclude:
    - rvm: 1.9.3
      env: TEST="test/test_*"
    - rvm: 1.9.3
      env: TEST="test/test_standard.rb"
    - rvm: jruby-19mode
      env: TEST="test/test_*"
    - rvm: jruby-19mode
      env: TEST="test/test_standard.rb"
    - rvm: jruby-19mode
      env: DISABLE_REFINEMENTS=1 TEST="test/test_*"
  allow_failures:
    - rvm: ruby-head
